### ISSUE TITLE
2 Ideas/Requests: New player commemoration, Photo booth

### ISSUE THREAD

**Issue by EmpathyHeals** [Zedly/Luma#1]
Hi, I love the Luma plugin! Thank you for making it! As I've been using it on my server for the past couple weeks I've gotten some ideas that my players thought would be cool to have for expanding the plugin and I was wondering if the following can be possible: 

1) New player snapshot: many times players ask "I wonder when I joined the server" or look back through forums/discord for their first entries and get nostalgic. It would be neat if Luma could either take an automatic screenshot of new players upon join within their first few minutes on the server. Then, add Welcome to Server, Playername! ~Date. And /give to player as a map of 3x3 or whatever size and keep a file saved for admins to access later, and be able to pull up the maps any time for players to commemorate their first day. Or make a New Player photo booth admins can place near where players spawn, and those who want to commemorate their first day can step in and take a photo of themselves on the day they joined.

2) Photo booths: basically a booth that admins can add in various placer or let builders add to various builds (like towns, entertainment parks, etc.). These could have "backgrounds to choose from" that are a collections of pre-selected images admins choose. Then players and their friends can step in and make a few selections. Like background, filter, a caption. If the background is too hard to do (and separate the player skin from the background image) then just a screenshot, Then upload this screenshot somewhere that applies a filter and writes a caption, and maybe if possible allow the player to see them and choose one (either in game or through a link). Then once they choose it the plugin can /give a map to the player. Maybe allow the booth to charge different prices for different sizes, captions, or any overlays. 

Thanks again for making this plugin!
Emp

**Comment by Zedly** [comment]
Hi, glad you enjoy the plugin! While an easy way to submit pictures directly to the server's file system would be very convenient, it would open a pretty large attack surface that's not worth it to save the 30 seconds it takes to put a screenshot on Imgur.

The photo backdrop sounds like a fun idea, but again it wouldn't actually save much effort compared to just grabbing a suitable background image from the web.

If I understand correctly, you're suggesting the server take a picture of the newly joined player? Unfortunately that's not something servers can do :)

Thank you for the feedback!
